DROP DATABASE IF EXISTS students;
CREATE DATABASE students DEFAULT CHARACTER SET utf8;
use students;
CREATE TABLE IF NOT EXISTS student(
  id INT UNSIGNED AUTO_INCREMENT,
  student_id INT UNSIGNED,
  name VARCHAR(32),
  age SMALLINT,
  sex VARCHAR(8),
  birthday DATE,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
